"""add client table

Revision ID: 394434ba987f
Revises: 
Create Date: 2024-11-08 18:22:39.348206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394434ba987f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.execute(sa.schema.CreateSequence(sa.schema.Sequence('id_seq'), if_not_exists=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.DropSequence(sa.schema.Sequence('id_seq'), if_exists=True))
    op.drop_table('clients')
    # ### end Alembic commands ###
